#!/usr/bin/env bash

set -eux

SCRIPT_DIR=$PWD
VIM_DEPENDENCY_DIR="$HOME/.vim/pack/$(whoami)/start"

echo "Vim dependencies will be cloned in '$VIM_DEPENDENCY_DIR'"
mkdir -pv $VIM_DEPENDENCY_DIR
cd $VIM_DEPENDENCY_DIR

DEPS=(
  airblade/vim-gitgutter
  altercation/vim-colors-solarized
  jiangmiao/auto-pairs
  jidn/vim-dbml
  jparise/vim-graphql
  keith/rspec.vim
  maxmellon/vim-jsx-pretty
  mileszs/ack.vim
  pangloss/vim-javascript
  scrooloose/nerdtree
  sstallion/vim-wildignore
  tpope/vim-abolish
  tpope/vim-commentary
  tpope/vim-endwise
  tpope/vim-fugitive
  tpope/vim-rails
  tpope/vim-surround
  vim-ruby/vim-ruby
  wincent/command-t
  wincent/terminus
)

for DEP in ${DEPS[@]}; do
  git clone --verbose "https://github.com/$DEP.git"
done

echo "Creating symlinks for dotfiles..."
cd $SCRIPT_DIR
DOTFILES=$(git ls-files | grep "^\.")
echo "$DOTFILES" | xargs -t -I % ln -sv "$SCRIPT_DIR/"% "$HOME"

echo "Creating symlink for wildignore"
ln -sv "$SCRIPT_DIR/wildignore" "$HOME/.vim/"

cd "$VIM_DEPENDENCY_DIR/command-t"
make
