#!/bin/bash

set -e

SCRIPT_DIR=$PWD
VIM_DEPENDENCY_DIR="$HOME/.vim/pack/$(whoami)/start/"

if [ ! -d "$VIM_DEPENDENCY_DIR" ]; then
  echo "Making directory '$VIM_DEPENDENCY_DIR' to clone dependencies"
  mkdir -p $VIM_DEPENDENCY_DIR

  DEPS=(
    airblade/vim-gitgutter.git
    altercation/vim-colors-solarized.git
    jiangmiao/auto-pairs.git
    keith/rspec.vim.git
    mileszs/ack.vim.git
    mxw/vim-jsx.git
    pangloss/vim-javascript.git
    scrooloose/nerdtree.git
    sstallion/vim-wildignore.git
    tpope/vim-abolish.git
    tpope/vim-commentary.git
    tpope/vim-endwise.git
    tpope/vim-fugitive.git
    tpope/vim-rails.git
    tpope/vim-surround.git
    vim-ruby/vim-ruby.git
    wincent/command-t.git
    wincent/terminus.git
  )

  echo "Cloning dependencies in '$VIM_DEPENDENCY_DIR'"
  cd $VIM_DEPENDENCY_DIR

  for DEP in ${DEPS[@]}; do
    REPO="https://github.com/$DEP"
    echo "Cloning from $REPO..."
    git clone $REPO --verbose
  done
else
  echo "'$VIM_DEPENDENCY_DIR' already exists. Skipping cloning dependencies."
fi

echo "Creating symlinks for dotfiles..."
cd $SCRIPT_DIR
DOTFILES=$(git ls-files | grep "^\.")
echo "$DOTFILES" | xargs -t -I % ln -sv "$SCRIPT_DIR/"% "$HOME"

echo "Creating symlink for wildignore"
ln -sv "$SCRIPT_DIR/wildignore" "$HOME/.vim/"

cd "$VIM_DEPENDENCY_DIR/command-t"
rake make
